version: '3.5'
services:
  typo3:
    depends_on:
    - redis
    environment:
      REDIS_HOST: redis
    networks:
      typo3-redis:

  redis:
    image: redis:alpine
    networks:
      typo3-redis:
    restart: ${RESTART}

networks:
  typo3-redis:
